name: "Code Analysis - GitHub Super Linter"
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "edited"
      - "reopened"
      - "synchronize"
jobs:
  code-analysis-ghsl:
    name: "Code Analysis - GitHub Super Linter"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
        with:
          fetch-depth: 0
      - name: "Checkout Pull Request"
        if: "${{github.event_name == 'pull_request'}}"
        run: "git checkout HEAD^2"
      - name: "Analyze Repository"
        uses: "github/super-linter@v3.14.3"
        env:
          DISABLE_ERRORS: "true"
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          LINTER_RULES_PATH: ".github/linters"
          LOG_FILE: "super-linter.log"
          LOG_LEVEL: "VERBOSE"
          MULTI_STATUS: "true"
          OUTPUT_DETAILS: "detailed"
          OUTPUT_FOLDER: "super-linter-output"
          VALIDATE_ALL_CODEBASE: "true"
      - name: "Upload Result"
        uses: "actions/upload-artifact@v2.2.1"
        with:
          if-no-files-found: "warn"
          name: "super-linter-output"
          path: "super-linter-output"